# docker-compose.dev.yml
version: '3.8'

services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: library_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./library-backend
      dockerfile: Dockerfile.dev
    environment:
      GIN_MODE: debug
      LOG_LEVEL: debug
      DB_NAME: library_dev
    volumes:
      - ./library-backend:/app
      - go_mod_cache:/go/pkg/mod
    ports:
      - "8080:8080"
      - "2345:2345"  # Delve debugger
    command: ["air", "-c", ".air.toml"]

  frontend:
    build:
      context: ./library-frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8080/api/v1
    volumes:
      - ./library-frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  postgres_dev_data:
  go_mod_cache:
  node_modules: